[theme]
primaryColor = "#4f46e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#0f0f14"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false